font_family JetBrainsMono Nerd Font Mono

shell zsh

url_style curly

remember_window_size no

background_opacity 		0.74
scrollbar_handle_opacity 	0 
scrollbar_track_opacity 	0
scrollbar_track_hovor_opacity 	0

confirm_os_window_close 0

sync_to_monitor no

map ctrl+c copy_or_interrupt
