listener {
    timeout = 300                                 # 5 minutes
    on-timeout = hyprlock                         # Command to run when timeout has passed
}

listener {
    timeout = 600                                 # 10 minutes
    on-timeout = systemctl suspend                # Suspend computer (works natively on Arch)
}